# Generated by Django 4.0.5 on 2022-07-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('item_price', models.FloatField()),
                ('item_discription', models.TextField()),
            ],
        ),
    ]
