# Generated by Django 4.0.5 on 2022-07-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floweritem',
            name='item_category',
            field=models.CharField(blank=True, choices=[('Погребения', 'Погребения'), ('Сватба', 'Сватба'), ('Други', 'Други')], max_length=100, null=True),
        ),
    ]
